// <auto-generated />
using System;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(SkiTripContext))]
    [Migration("20260925115612_UserModelUpdate")]
    partial class UserModelUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Infra.Models.CityLocation", b =>
                {
                    b.Property<Guid>("CityLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CityDirectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("CityLocationId");

                    b.HasIndex("CityDirectorId");

                    b.ToTable("CityLocations");
                });

            modelBuilder.Entity("Infra.Models.SkiGear", b =>
                {
                    b.Property<Guid>("SkiGearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GearName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GearOwnerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStoredOnSite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StorageLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("SkiGearId");

                    b.HasIndex("GearOwnerId");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("SkiGears");
                });

            modelBuilder.Entity("Infra.Models.SkiTrip", b =>
                {
                    b.Property<Guid>("SkiTripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPastTrip")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoundTrip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalMiles")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TripCoordinatorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripDestinationArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripDestinationDepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripDestinationLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripOriginArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripOriginCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripOriginDepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripOriginLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TripTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SkiTripId");

                    b.HasIndex("TripCoordinatorId");

                    b.ToTable("SkiTrips");
                });

            modelBuilder.Entity("Infra.Models.StorageLocation", b =>
                {
                    b.Property<Guid>("StorageLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkiStorageCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StorageLocationId");

                    b.ToTable("StorageLocations");
                });

            modelBuilder.Entity("Infra.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkiTripUser", b =>
                {
                    b.Property<Guid>("AttendingTripsSkiTripId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegisteredUsersUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AttendingTripsSkiTripId", "RegisteredUsersUserId");

                    b.HasIndex("RegisteredUsersUserId");

                    b.ToTable("SkiTripUser");
                });

            modelBuilder.Entity("Infra.Models.CityLocation", b =>
                {
                    b.HasOne("Infra.Models.User", "CityDirector")
                        .WithMany()
                        .HasForeignKey("CityDirectorId");

                    b.Navigation("CityDirector");
                });

            modelBuilder.Entity("Infra.Models.SkiGear", b =>
                {
                    b.HasOne("Infra.Models.User", "GearOwner")
                        .WithMany("PersonalGear")
                        .HasForeignKey("GearOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infra.Models.StorageLocation", "StorageLocation")
                        .WithMany("StoredGear")
                        .HasForeignKey("StorageLocationId");

                    b.Navigation("GearOwner");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("Infra.Models.SkiTrip", b =>
                {
                    b.HasOne("Infra.Models.User", "TripCoordinator")
                        .WithMany("CoordinatedTrips")
                        .HasForeignKey("TripCoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TripCoordinator");
                });

            modelBuilder.Entity("SkiTripUser", b =>
                {
                    b.HasOne("Infra.Models.SkiTrip", null)
                        .WithMany()
                        .HasForeignKey("AttendingTripsSkiTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infra.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RegisteredUsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infra.Models.StorageLocation", b =>
                {
                    b.Navigation("StoredGear");
                });

            modelBuilder.Entity("Infra.Models.User", b =>
                {
                    b.Navigation("CoordinatedTrips");

                    b.Navigation("PersonalGear");
                });
#pragma warning restore 612, 618
        }
    }
}
